/**
 * Inline Suggestion Card - Create proposals from AI suggestions
 */

import * as React from 'react';
import {
  makeStyles,
  tokens,
  Card,
  Button,
  Text,
  Body1,
  Caption1,
  Badge,
} from '@fluentui/react-components';
import {
  Sparkle20Filled,
  Add20Regular,
  Dismiss20Regular,
} from '@fluentui/react-icons';
import { useProposalStore } from '../state/useProposalStore';
import { ProposalStatus, ApprovalState } from '../types';

interface InlineSuggestionCardProps {
  /** Type of suggestion context */
  context: 'email' | 'document' | 'chat';
  /** Suggestion title */
  title: string;
  /** Suggestion description */
  description: string;
  /** Proposed proposal data */
  proposalData: {
    title: string;
    clientName: string;
    clientId: string;
    opportunityValue: number;
    dueDate: Date;
  };
  /** Optional callback after proposal is created */
  onProposalCreated?: (proposalId: string) => void;
  /** Whether card can be dismissed */
  dismissible?: boolean;
}

const useStyles = makeStyles({
  card: {
    padding: tokens.spacingVerticalM,
    marginTop: tokens.spacingVerticalM,
    marginBottom: tokens.spacingVerticalM,
    backgroundColor: tokens.colorBrandBackground2,
    borderLeft: `3px solid ${tokens.colorBrandForeground1}`,
    position: 'relative',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: tokens.spacingVerticalS,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    color: tokens.colorBrandForeground1,
  },
  content: {
    marginBottom: tokens.spacingVerticalM,
  },
  proposalDetails: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
    marginTop: tokens.spacingVerticalS,
    marginBottom: tokens.spacingVerticalS,
  },
  actions: {
    display: 'flex',
    gap: tokens.spacingHorizontalS,
    alignItems: 'center',
  },
  createdMessage: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    padding: tokens.spacingVerticalS,
    backgroundColor: tokens.colorPaletteGreenBackground2,
    borderRadius: tokens.borderRadiusMedium,
    marginTop: tokens.spacingVerticalS,
  },
});

export const InlineSuggestionCard: React.FC<InlineSuggestionCardProps> = ({
  context,
  title,
  description,
  proposalData,
  onProposalCreated,
  dismissible = true,
}) => {
  const styles = useStyles();
  const [isDismissed, setIsDismissed] = React.useState(false);
  const [isCreated, setIsCreated] = React.useState(false);
  const createProposal = useProposalStore((s) => s.createProposal);
  const setActiveProposal = useProposalStore((s) => s.setActiveProposal);

  const handleCreateProposal = React.useCallback(() => {
    const now = new Date();
    
    // Create proposal with the suggested data
    const proposalId = createProposal({
      title: proposalData.title,
      clientName: proposalData.clientName,
      clientId: proposalData.clientId,
      opportunityValue: proposalData.opportunityValue,
      status: ProposalStatus.DRAFT,
      sections: [
        {
          id: '', // Will be generated by store
          title: 'Executive Summary',
          content: `This proposal outlines our recommended approach for ${proposalData.clientName}.`,
          confidence: 0.5,
          sources: [],
          approvalState: ApprovalState.DRAFT,
          order: 1,
          lastModified: now,
          modifiedBy: 'AI Copilot',
          wordCount: 12,
        },
      ],
      openQuestions: [],
      nudges: [],
      createdAt: now,
      lastModified: now,
      dueDate: proposalData.dueDate,
      owner: {
        id: 'user-1',
        name: 'Current User',
        email: 'user@company.com',
      },
      overallConfidence: 0.5,
      totalWordCount: 12,
    });

    // Set as active proposal
    setActiveProposal(proposalId);
    setIsCreated(true);

    // Callback
    if (onProposalCreated) {
      onProposalCreated(proposalId);
    }

    // Log for demo purposes
    console.log('✅ Created proposal:', proposalId, proposalData);
  }, [createProposal, setActiveProposal, proposalData, onProposalCreated]);

  const handleDismiss = React.useCallback(() => {
    setIsDismissed(true);
  }, []);

  if (isDismissed) {
    return null;
  }

  return (
    <Card className={styles.card}>
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <Sparkle20Filled />
          <Text weight="semibold">Copilot Suggestion</Text>
        </div>
        {dismissible && !isCreated && (
          <Button
            appearance="subtle"
            icon={<Dismiss20Regular />}
            size="small"
            onClick={handleDismiss}
            title="Dismiss suggestion"
          />
        )}
      </div>

      <div className={styles.content}>
        <div style={{ marginBottom: tokens.spacingVerticalXS }}>
          <Text weight="semibold">{title}</Text>
        </div>
        <Caption1>{description}</Caption1>

        <div className={styles.proposalDetails}>
          <Badge appearance="tint" color="brand">
            {proposalData.clientName}
          </Badge>
          <Badge appearance="tint" color="informative">
            ${(proposalData.opportunityValue / 1000).toFixed(0)}K
          </Badge>
          <Badge appearance="tint" color="subtle">
            Due: {proposalData.dueDate.toLocaleDateString()}
          </Badge>
        </div>
      </div>

      {isCreated ? (
        <div className={styles.createdMessage}>
          <Sparkle20Filled style={{ color: tokens.colorPaletteGreenForeground1 }} />
          <Text weight="semibold" style={{ color: tokens.colorPaletteGreenForeground1 }}>
            Proposal created and set as active! Check the store to see it.
          </Text>
        </div>
      ) : (
        <div className={styles.actions}>
          <Button
            appearance="primary"
            icon={<Add20Regular />}
            onClick={handleCreateProposal}
          >
            Create Proposal
          </Button>
          <Caption1>Quick start with AI assistance</Caption1>
        </div>
      )}
    </Card>
  );
};

export default InlineSuggestionCard;

